
FROM node:14
ADD https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh /tmp/install_nvm.sh
RUN chmod +x /tmp/install_nvm.sh && \
    /tmp/install_nvm.sh 
SHELL ["/bin/bash", "-c"]
RUN source $HOME/.nvm/nvm.sh && nvm install node && nvm alias default node
COPY . .
#COPY /root/devops-fullstack-app/frontend/package*.json ./
WORKDIR /devops-fullstack-app/frontend/
EXPOSE 3000
SHELL ["/bin/bash", "-c"]
RUN npm install
CMD ["npm" , "start"]
